### ISSUE TITLE
Illegal use of '**' in exclude path

### ISSUE THREAD

**Issue by kochis** [github/codeql-cli-binaries#120]
Hello, our codeQL config file has the following:
```yml
name: "CodeQL Config"

paths-ignore:
  - '**/static/storybook/**'
```

Which has been working for well over a year. Without any changes to the file, we started seeing the following failure today:
```
/opt/hostedtoolcache/CodeQL/0.0.0-20220[31](https://github.com/radarlabs/frontend/runs/5835570295?check_suite_focus=true#step:5:31)1/x64/codeql/codeql database trace-command /home/runner/work/_temp/codeql_databases/javascript -- /opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/javascript/tools/autobuild.sh
  Running command in /home/runner/work/frontend/frontend: [/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/javascript/tools/autobuild.sh]
  [2022-04-05 14:[39](https://github.com/radarlabs/frontend/runs/5835570295?check_suite_focus=true#step:5:39):39] [build-stderr] Skipping path /home/runner/work/frontend/frontend/**/static/storybook/**, which does not exist.
  [2022-04-05 14:39:39] [build-stderr] Illegal use of '**' in exclude path
  Error: 4-05 14:39:39] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/javascript/tools/autobuild.sh])
  A fatal error occurred: Exit status 1 from command: [/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/javascript/tools/autobuild.sh]
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/codeql' failed with exit code 2
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/codeql' failed with exit code 2
      at toolrunnerErrorCatcher (/home/runner/work/_actions/github/codeql-action/v1/lib/toolrunner-error-catcher.js:86:19)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Object.extractScannedLanguage (/home/runner/work/_actions/github/codeql-action/v1/lib/codeql.js:5[44](https://github.com/radarlabs/frontend/runs/5835570295?check_suite_focus=true#step:5:44):13)
      at async createdDBForScannedLanguages (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze.js:79:13)
      at async finalizeDatabaseCreation (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze.js:96:5)
      at async runFinalize (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze.js:260:5)
      at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze-action.js:78:9)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze-action.js:212:9)
 ```
 
 Wondering if there were any recent changes to the spec, or if we need to update our file. Happy to provide more details if needed.

**Comment by edoardopirovano** [comment]
Greetings, thanks for raising this with us. It looks like we accidentally made a change that broke your workflow - our apologies for that! We've now reverted that change so I'm hopeful that things should be working again for you. Would you mind trying your workflow again and letting is know if it's working now? Many thanks!

**Comment by kochis** [comment]
@edoardopirovano Looks like it's resolved, thanks for the quick reply! Feel free to close this out.

**Comment by edoardopirovano** [comment]
Glad to hear that, and sorry once again it broke in the first place!
