### ISSUE TITLE
CatastrophicError on --command="" with codeql database create

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [github/codeql-cli-binaries#23]
Running

`codeql database create db --language cpp --command=""`

returns

```
Initializing database at /Users/user/codeql-home/eigen/db.
Running command [] in /Users/user/codeql-home/eigen.
Oops! A fatal internal error occurred.
com.semmle.util.exception.CatastrophicError: Error when interpreting a constructed plumbing child command line:
codeql database trace-command --working-dir=/Users/user/codeql-home/eigen -- /Users/user/codeql-home/eigen/db
Missing required parameter: <command>
(eventual cause: MissingParameterException "Missing required parameter: <command>")
        at com.semmle.cli2.picocli.PlumbingRunner.parse(PlumbingRunner.java:223)
        at com.semmle.cli2.picocli.PlumbingRunner.run(PlumbingRunner.java:75)
        at com.semmle.cli2.picocli.SubcommandCommon.runPlumbingInProcess(SubcommandCommon.java:130)
        at com.semmle.cli2.database.CreateCommand.executeSubcommand(CreateCommand.java:94)
        at com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:383)
        at com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:174)
        at com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:182)
        at com.semmle.cli2.CodeQL.main(CodeQL.java:89)
Caused by: picocli.CommandLine$MissingParameterException: Missing required parameter: <command>
        at picocli.CommandLine$Interpreter.assertNoMissingParameters(CommandLine.java:12056)
        at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:11050)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:11039)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:10916)
        at picocli.CommandLine.parseArgs(CommandLine.java:1271)
        at com.semmle.cli2.picocli.PlumbingRunner.parse(PlumbingRunner.java:207)
        ... 7 more
```

Nothing critical but I thought it would be worth sharing.

**Comment by hmakholm** [comment]
Thanks. The `CatastrophicError` means there's a real bug somewhere, not just cosmetics. Apparently something somewhere doesn't like an empty string being used as an argument value. I'll investigate.

**Comment by hmakholm** [comment]
I've merged a change that gives a friendlier error message in this case; it will be in the next release.

(internal PR https://git.semmle.com/Semmle/code/pull/36746)
