### ISSUE TITLE
CodeQL Analysis Error: codeql.exe fails with exit code 100

### ISSUE THREAD

**Issue by egorodet** [github/codeql-cli-binaries#66]
**Description of the issue**

CodeQL analysis has started failing with a huge 20000 lines debug output which finishes with the following:

```
Scheduler is idle before completion of internal stage {139.16}FlowVar::FlowVar#class#f FlowVar::FlowVar::getAnAccess_dispred#ff FlowVar::FlowVar::definedPartiallyAt_dispred#ff FlowVar::FlowVar::definedByInitialValue_dispred#ff FlowVar::FlowVar::definedByExpr_dispred#fff FlowVar::FlowVar::toString_dispred#ff FlowVar::FlowVar::getLocation_dispred#ff FlowVar::FlowVar::reachesRefParameter_dispred#ff
  If you see this error in a production run with the latest CLI, please file a report including the above graph dump.
  	at com.semmle.inmemory.scheduler.EvaluationSchedule.throwErrorIncludingGraphDump(EvaluationSchedule.java:165)
  	at com.semmle.inmemory.scheduler.StageTask.lambda$evaluateAsync$1(StageTask.java:123)
  	at com.semmle.inmemory.scheduler.ExecutionScheduler$IdleNotifier.trigger(ExecutionScheduler.java:724)
  	at java.base/java.lang.Iterable.forEach(Unknown Source)
  	at com.semmle.inmemory.scheduler.ExecutionScheduler.checkIdle(ExecutionScheduler.java:694)
  	at com.semmle.inmemory.scheduler.ExecutionScheduler.finishRunner(ExecutionScheduler.java:617)
  	at com.semmle.inmemory.scheduler.ExecutionScheduler.runnerMain(ExecutionScheduler.java:575)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  	at java.base/java.lang.Thread.run(Unknown Source)
  Error: The process 'C:\hostedtoolcache\windows\CodeQL\0.0.0-20210503\x64\codeql\codeql.exe' failed with exit code 100
  Error: Error running analysis for cpp: Error: The process 'C:\hostedtoolcache\windows\CodeQL\0.0.0-20210503\x64\codeql\codeql.exe' failed with exit code 100
  CodeQLAnalysisError: Error running analysis for cpp: Error: The process 'C:\hostedtoolcache\windows\CodeQL\0.0.0-20210503\x64\codeql\codeql.exe' failed with exit code 100
      at runQueries (D:\a\_actions\github\codeql-action\v1\lib\analyze.js:130:19)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    name: 'CodeQLAnalysisError',
    queriesStatusReport: { analyze_failure_language: 'cpp' }
```

- See full debug output of the CodeQL in MethaneKit actions: https://github.com/egorodet/MethaneKit/runs/2694745896?check_suite_focus=true
- See attached log of the CodeQL failure: [CodeQL-Failure-Log.txt](https://github.com/github/codeql/files/6561977/CodeQL-Failure-Log.txt)
- Note that CodeQL fails on Windows only, while Linux and MacOS checks are running fine. Previous commits were passing CodeQL checks on all platforms successfully.

**Comment by hmakholm** [comment]
Hmm, actually all of the stage tasks of `{140}` still exist in the graph, even though the progress logging said the query completed.

What's worse, the _internal_ stage `{140.13}` is actively sourcing demand even though it has completed far enough for the subsequent stages to be created.

**Comment by hmakholm** [comment]
@egorodet, thanks for the bug report. We have identified the underlying reason and are working on a fix to be included in the next release of the CodeQL engine.

The mechanism of the bug is related to how we evaluate several queries in parallel, though it's not quite as nondeterministic as the typical timing-dependent cnocurrency bug. If rerunning the analysis doesn't resolve it for you, you should be able to avoid it definitely by turning off parallelism with this in your workflow file:
```
- uses: codeql-action/analyze@v1
  with:
    threads: 1
```
There will be a cost in response times, so be sure to remove the threads argument again after several weeks when the fixed CodeQL is out.
